### ISSUE TITLE
bin/sh vs. bin/bash

### ISSUE THREAD

**Issue by PragTob** [dsyer/main-branch-switch#2]
Hi there,

first thanks so much for creating this :green_heart: 

Running this directly yields the following problems for me:

```
tobi@speedy:~/github/main-branch-switch(main)$ main_branch.sh 
/home/tobi/github/main-branch-switch/main_branch.sh: 5: [: unexpected operator
/home/tobi/github/main-branch-switch/main_branch.sh: 25: [: unexpected operator
/home/tobi/github/main-branch-switch/main_branch.sh: 32: [: unexpected operator
/home/tobi/github/main-branch-switch/main_branch.sh: 39: [: unexpected operator
/home/tobi/github/main-branch-switch/main_branch.sh: 46: /home/tobi/github/main-branch-switch/main_branch.sh: function: not found
```

Changing the "shebang" lines to `#!/bin/bash` in _both_ .sh files solved it for me. I suspect this is some kind of linux vs. mac difference. I'm running Linux Mint based on Ubuntu 18.04.

Happy to do a PR with this tiny chance, but I'm unsure if it would work on Mac. If it does, it sure would help some linux folks :)

Thanks again!

**Comment by dsyer** [comment]
I use Linux, so it’s not that. I think it would work for me with explicit bash shell, so send a Pr if you want and I’ll check it out.

**Comment by PragTob** [comment]
Huh weird I wonder why it fails then. Will send PR, thanks!
